-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.5-10.0.5-MariaDB-1~wheezy-log - mariadb.org binary distribution
-- Server OS:                    debian-linux-gnu
-- HeidiSQL Version:             8.1.0.4615
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for MusicPlayer
CREATE DATABASE IF NOT EXISTS `MusicPlayer` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci */;
USE `MusicPlayer`;


-- Dumping structure for table MusicPlayer.MusicStore
CREATE TABLE IF NOT EXISTS `MusicStore` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Title` longtext COLLATE utf8_polish_ci,
  `PictureUrl` longtext COLLATE utf8_polish_ci,
  `TrackUrl` longtext COLLATE utf8_polish_ci,
  `Price` float DEFAULT '0',
  `Artist` longtext COLLATE utf8_polish_ci,
  `Album` longtext COLLATE utf8_polish_ci,
  `About` longtext COLLATE utf8_polish_ci,
  `Lyrics` longtext COLLATE utf8_polish_ci,
  `Genre` longtext COLLATE utf8_polish_ci,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

-- Dumping data for table MusicPlayer.MusicStore: ~5 rows (approximately)
/*!40000 ALTER TABLE `MusicStore` DISABLE KEYS */;
REPLACE INTO `MusicStore` (`Id`, `Title`, `PictureUrl`, `TrackUrl`, `Price`, `Artist`, `Album`, `About`, `Lyrics`, `Genre`) VALUES
	(1, 'Now Get Busy', 'http://upload.wikimedia.org/wikipedia/en/8/83/Now_Get_Busy.jpg', 'http://mirrors.creativecommons.org/ccmixter/contrib/Wired/Beastie%20Boys%20-%20Now%20Get%20Busy.mp3', 4.99, 'Beastie Boys', 'The Wired CD', '"Now Get Busy" is a song by American hip hop group the Beastie Boys, released in 2004. The song appeared on the compilation album The Wired CD. The song is also available for purchase on iTunes.\r\n\r\nThe song is licensed under the Creative Commons Noncommercial Sampling Plus license, allowing noncommercial file-sharing and noncommercial sampling.\r\n\r\nJapanese copies of To the 5 Boroughs include this song as the sixteenth and final track.', '\r\n\r\nWhether in a penthouse or a cave dweller\r\nI can tell you \'bout now I\'m not a fortune teller\r\nGrab a treat from Yosi my muffin seller\r\nGot mad technique like Rudy Van Gelder\r\nAnd yes I got a plan I\'m a carry out it\r\nYes I\'m pro-choice I\'m a scream and shout it\r\n\r\nYes I love life and I try not to doubt it\r\nYes I\'m gonna party \'cause I\'m \'bout it \'bout it\r\nWhen it rains I don\'t use an umbrella\r\nWhen I write rhymes, I use indelible ink\r\nThat will make you think\r\nFlowing like water that you love to drink\r\n\r\nNow get busy\r\n\r\nSweet like a [Incomprehensible] with Nutella\r\nCreamy like buffalo mozzarella\r\nSneaking around you know I smell ya\r\nWell I play ya like a peanut and throw the shell ya\r\nWell I could give a fuzz if ya think you\'re a baller\r\nI gets \'em [Incomprehensible] well you fall smaller\r\n\r\nMiddle school rapper and a proud yes y\'aller\r\nIf ya think about your grandma go ahead call her\r\nFrom the East Coast so I don\'t say hella\r\nAt the mic stand my performance is stellar\r\nPop the tape in and I listen to fella\r\nI give a little shout to Nelson Mandela\r\n\r\nNow get busy\r\n\r\nKnown for the words that make you scream and holler\r\nI\'m Count Dooku to your Queen Amidala\r\nGive a shout to Spiro or John Waller\r\nI\'m a student of the game and a bona fide scholar\r\nSo ease up on the bong to ease that coughin\'\r\nButter\'s on the table now watch it soften\r\n\r\nBring in those beats and I\'m a bring them often\r\nI\'m a keep rappin\' when I\'m in my coffin\r\nLike a mind gone mad that is unwinding\r\nIn a padded room the walls you\'re climbing\r\nDon\'t sign on the line if it looks binding\r\nYa have to get loose and find the lining\r\n\r\nNow get busy\r\nNow get busy\r\n\r\nRead more: Beastie Boys - Now Get Busy Lyrics | MetroLyrics\r\n', 'hip hop'),
	(4, 'My Fair Lady', 'http://upload.wikimedia.org/wikipedia/en/9/97/Wired_cd_cover.jpg', 'http://mirrors.creativecommons.org/ccmixter/contrib/Wired/David%20Byrne%20-%20My%20Fair%20Lady.mp3', 4.99, 'David Byrne', 'The Wired CD', 'David Byrne has released a handful of books - including Arboretum a collection of sketches of some of his favorite trees and The New Sins about sin in the 21st century. He has also made several public art installations, speaking engagements on art and technology, and PowerPoint presentations. In addition to a recording career as a solo artist, he also founded the record labels Luaka Bop and Todo Mundo.', 'Look, is this the real thing?\r\nWhen you caught my eye\r\nHow you looked at me, from the pages of a magazine\r\nNow you\'re always, always on my mind\r\n\r\nEvery color, line and feature\r\nNever age and never tire\r\nIn my sleep and in my dreams at night\r\nCalls to me a strange attraction\r\nWith your beauty and your passion\r\nYou are art and art will never change\r\n\r\nSuch a perfect replica\r\nEvery pore and hair\r\nEvery pencil mark\r\nYou\'re such a perfect imitation of\r\nAnd that it seems, seems you\'re almost here\r\nEvery color, line and feature\r\nNever age and never tire\r\nIn my sleep and in my dreams at night\r\nCalls to me a strange attraction\r\nWith your beauty and your passion\r\nYou are art and art will never change\r\n\r\nYou are just an illustration\r\nThis is just a simulation\r\nLines and pixels on a piece of paper\r\n\r\nYou can see me slowly changing\r\nBut forever you\'ll remain\r\nAnd you have time because you will live forever\r\n\r\nEvery color, line and feature\r\nNever age and never tire\r\nIn my sleep and in my dreams at night\r\nCalls to me strange attraction\r\nWith your beauty and your passion\r\nYou are art and art will never change\r\nTake me away (x4)\r\n', 'new wave'),
	(5, 'Wadidyusay?', 'http://i.ytimg.com/vi/eImoYmqe-S8/0.jpg', 'http://mirrors.creativecommons.org/ccmixter/contrib/Wired/Zap%20Mama%20-%20Wadidyusay.mp3', 4.99, 'Zap Mama', 'The Wired CD', 'From the Album Ancestry in Progress... I do not own rights on this song and figuring photos, Rights are all properties reserved to their respective owners', NULL, 'country'),
	(6, 'One Big Holiday', 'http://liveforlivemusic.com/wp-content/uploads/2013/06/My-Morning-Jacket-One-Big-Holiday-440881.jpg', 'http://mirrors.creativecommons.org/ccmixter/contrib/Wired/My%20Morning%20Jacket%20-%20One%20Big%20Holiday.mp3', 4.99, 'My Morning Jacket', 'The Wired CD', '"One Big Holiday" is a song by American rock band My Morning Jacket and is featured on their 2003 album It Still Moves. It is also featured on the band\'s 2006 live concert CD and DVD Okonokos. It is perhaps their most well-known song.\r\n\r\nDespite a lack of radio airplay the track has achieved some notoriety, which could be the result of several solid live performances, most notably on Late Night with Conan O\'Brien as well as several performances at the Bonnaroo Music Festival. Its signature guitar riff and the lyrics, telling the story of the band being "discovered", continue to make it a fan favorite and staple of live performances.\r\n\r\nThe song has made appearances on several soundtracks, most notably the 2007 film The Lookout and the 2006 film Stick It. The song also was featured in episode 6, season 4 of the Fox medical drama House.\r\n\r\nThe song is a playable track in Guitar Hero 5.', '"One Big Holiday"\r\n\r\nWakin\' up feelin\' good and limber\r\nWhen the telephone it ring\r\nWas a bad man from California\r\nTellin\' of a stone he\'d bring\r\n\r\nAnd of better days\r\nFrom this town, we\'d escape\r\nIf we holler loud and make our way\r\nWe\'d all live one big holiday\r\n\r\nSo we listened and up the river\r\nAnd recorded all the sounds\r\nWas some shakin\' and some record playin\'\r\nAll the leather kids were loud ', 'psychedelic rock'),
	(7, 'Revenge!', 'http://a1.mzstatic.com/us/r30/Music/70/c3/52/mzi.qhickkvx.170x170-75.jpg', 'http://mirrors.creativecommons.org/ccmixter/contrib/Wired/Spoon%20-%20Revenge!.mp3', 4.99, 'Spoon', 'The Wired CD', 'With their heady blend of precision punk and serpentine classic rock (the band has drawn comparisons to everyone from the Pixies and Sonic Youth to Elvis Costello and Tom Petty), enigmatic, Texas-based indie pop outfit Spoon went from underground press darlings to one of the genre’s premier commercially and critically acclaimed alternative rock acts. Formed in Austin by singer/guitarist Britt Daniel and drummer Jim Eno, Spoon released its debut EP, Nefarious, on the small Texas imprint Fluffer Records in 1994, eventually re-recording three of the songs for its 1996 full-length debut, Telephono, for Matador. The album was noisy, hook-filled, and generally well-received, but it wasn’t until 1997’s Soft Effects EP that the group began to hone in on the tight, minimalist pop that would become its forte. A brief and tumultuous affair with Elektra Records began in 1998 with the release of A Series of Sneaks, and quickly ended after the band was dropped in the midst of an internal company shake up (the record was reissued in 2002 on Merge with two bonus tracks that chronicled the group’s disappointment with major-label politics). It was with prominent indie label Merge that the band would go on to carve out its niche in the increasingly widening modern rock mainstream, specifically with Girls Can Tell (2001) and Kill the Moonlight (2002) (the latter spawned the single “The Way We Get By,” which appeared on the popular teen drama The O.C.), both of which found the group taking a more adventurous approach with their sound. 2005’s Gimme Fiction soared even higher, debuting at number 44 on the Billboard charts and selling over 160,000 copies, while 2007’s Ga Ga Ga Ga Ga made it to number ten and sold over 300,000 copies in the U.S., topping nearly every major critic’s year-end list. Spoon, who by this time had become a fixture on soundtracks, television programs, and late-night talk shows, released its seventh full-length album, Transference, on January 18, 2010. It debuted at number four on the Billboard 200. ', 'I\'ve gone out of my way\r\nBig, blank slate every day\r\nBig blank, canvas staring at me every day\r\n\r\nRevenge\r\nRevenge\r\nRevenge\r\n\r\nPush pin stuck in\r\nI\'ve got stuck in\r\n\r\nThe word\'s out\r\nI\'m not sure where I am\r\nHow I\'m gonna get back where I am\r\nWhat the real purpose is what I want\r\nWhat I want to reveal\r\n\r\nStuck in Dallas with the novelette\r\nGotta blink kids are staring at me like a set\r\nI fucked up, now I just won again\r\n\r\n(Revenge, Revenge, Revenge) I\'m not sure where I am\r\n(Revenge, Revenge, Revenge) How I\'m gonna get back where I am\r\n(Revenge, Revenge) What the real purpose is what I want\r\n(Revenge, Revenge) What I want to reveal ', 'pop'),
	(8, 'Oslodum', 'http://freemusicarchive.org/file/images/albums/Wired_Magazine_-_The_WIRED_CD_Rip_Sample_Mash_Share_-_2009113014304206.jpg?method=crop&width=290&height=290', 'http://mirrors.creativecommons.org/ccmixter/contrib/Wired/Gilberto%20Gil%20-%20Oslodum.mp3', 4.99, 'Gilberto Gil ', 'The Wired CD', NULL, 'Eu vou prá Oslo\r\nprá sair no Oslodum\r\no bloco ...\r\nda terra do bacalhau\r\nque, claro todo ano\r\ncaia neve ou faça sol\r\nvai prá avenida\r\nno dia de carnaval\r\neu vou.. eu vou..\r\n\r\nEu vou prá Oslo\r\nprá sair no Oslodum\r\no bloco ...\r\nda terra do bacalhau\r\nque, claro todo ano\r\ncaia neve ou faça sol\r\nvai prá avenida\r\nno dia de carnaval\r\n\r\nEu vou prá Oslo\r\nver a turma do pelô\r\ndo pelourinho, pelourinha, pelourão\r\neu vou pra Oslo aprender\r\n1 canto prá Xangô\r\nque, claro chama Thor\r\no filho do Trovão\r\n\r\nEu vou prá Oslo cantar\r\neu vou prá Oslo encantar\r\naquela moça, a mais bonita do lugar\r\nno pelourinho lourinho\r\nda cabecinha lourinha\r\ndo coração igual ao nosso\r\na palpitar ', 'punk '),
	(9, 'Relaxation Spa Treatment', 'http://freemusicarchive.org/file/images/albums/Wired_Magazine_-_The_WIRED_CD_Rip_Sample_Mash_Share_-_2009113014304206.jpg?method=crop&width=290&height=290', 'http://mirrors.creativecommons.org/ccmixter/contrib/Wired/Dan%20The%20Automator%20-%20Relaxation%20Spa%20Treatment.mp3', 4.99, 'Dan the Automator', 'The Wired CD', NULL, NULL, 'hip hop'),
	(11, 'DC 3000', 'http://img.mp3vol.com/images/albums/big/Thievery_Corporation/1999_-_DC_3000.jpg', 'http://mirrors.creativecommons.org/ccmixter/contrib/Wired/Thievery%20Corporation%20-%20Dc%203000.mp3', 4.99, 'Thievery Corporation', 'The Wired CD', 'Thievery Corporation is a Washington, D.C. based recording artist and DJ duo consisting of Rob Garza, Eric Hilton, and their supporting artists Rob Myers, Frank \'Booty Lock\' Mitchell, Jeff Franca and Ashish Vyas. Their music style mixes elements of dub, acid jazz, reggae, Indian classical, Middle Eastern, and Brazilian (such as bossa nova).', NULL, 'trip hop');
/*!40000 ALTER TABLE `MusicStore` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
